///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace StepEditText
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            //bool bBigMode = true;

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.MeasureText' at Center.", repo.SnapXUntitled.MeasureTextInfo, new RecordItemIndex(0));
            //repo.SnapXUntitled.MeasureText.MoveTo();
            //Delay.Milliseconds(200);
            //bBigMode = repo.SnapXUntitled.MeasureText.Visible;

            //if (bBigMode)
            //{
            //    repo.SnapXUntitled.TitleBar.Click("510;10");
            //    Delay.Milliseconds(200);
            //}
            //else
            //{
            //    repo.SnapXUntitled.SwitchToSensor.Click();
            //    Delay.Milliseconds(200);

            //    repo.SnapXUntitled.TitleBar.Click("510;10");
            //    Delay.Milliseconds(200);
            //}


            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LMenu}'.", new RecordItemIndex(3));
            //Keyboard.Press("{LMenu}");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'F'.", new RecordItemIndex(4));
            //Keyboard.Press("F");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'O'.", new RecordItemIndex(5));
            //Keyboard.Press("O");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(6));
            //Delay.Duration(2000, false);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'D:\\Joro\\GIT_Automations\\VERSION 3\\RoutineOne.mxy'.", new RecordItemIndex(7));
            //Keyboard.Press("D:\\Joro\\GIT_Automations\\VERSION 3\\RoutineOne.mxy");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}'.", new RecordItemIndex(8));
            //Keyboard.Press("{Delete}");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(9));
            //Keyboard.Press("{Return}");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.TitleBar' at Center.", repo.SnapXUntitled.TitleBarInfo, new RecordItemIndex(10));
            //repo.SnapXUntitled.TitleBar.Click();
            //Delay.Milliseconds(200);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LMenu}'.", new RecordItemIndex(11));
            //Keyboard.Press("{LMenu}");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'E'.", new RecordItemIndex(12));
            //Keyboard.Press("E");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'S'.", new RecordItemIndex(13));
            //Keyboard.Press("S");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXRoutineOneMxy.TitleText' at Center.", repo.SnapXRoutineOneMxy.TitleTextInfo, new RecordItemIndex(14));
            //repo.SnapXRoutineOneMxy.TitleText.Click();
            //Delay.Milliseconds(200);

            //string strTitleText = repo.SnapXRoutineOneMxy.TitleText.TextValue;
            //string strHardcodedTitleText = "Step Edit Routine";
            //UtilityRun.InspectText(strTitleText, strHardcodedTitleText);
            //Delay.Milliseconds(200);

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXRoutineOneMxy.PromptText' at Center.", repo.SnapXRoutineOneMxy.PromptTextInfo, new RecordItemIndex(15));
            //repo.SnapXRoutineOneMxy.PromptText.Click();
            //Delay.Milliseconds(200);

            //string strpromptText = repo.SnapXRoutineOneMxy.PromptText.TextValue;


            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXRoutineOneMxy.StartAtStepText' at Center.", repo.SnapXRoutineOneMxy.StartAtStepTextInfo, new RecordItemIndex(16));
            //repo.SnapXRoutineOneMxy.StartAtStepText.Click();
            //Delay.Milliseconds(200);

            //string strStarttext = repo.SnapXRoutineOneMxy.StartAtStepText.TextValue;


            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXRoutineOneMxy.EndAtStepText' at Center.", repo.SnapXRoutineOneMxy.EndAtStepTextInfo, new RecordItemIndex(17));
            //repo.SnapXRoutineOneMxy.EndAtStepText.Click();
            //Delay.Milliseconds(200);

            //string strEndText = repo.SnapXRoutineOneMxy.EndAtStepText.TextValue;


            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXRoutineOneMxy.WholeWindow' at Center.", repo.SnapXRoutineOneMxy.WholeWindowInfo, new RecordItemIndex(18));
            //repo.SnapXRoutineOneMxy.WholeWindow.Click();
            //Delay.Milliseconds(200);

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXRoutineOneMxy.ButtonOK' at Center.", repo.SnapXRoutineOneMxy.ButtonOKInfo, new RecordItemIndex(19));
            //repo.SnapXRoutineOneMxy.ButtonOK.Click();
            //Delay.Milliseconds(200);

            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(20));
            //Delay.Duration(3000, false);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'o'.", new RecordItemIndex(21));
            //Keyboard.Press("o");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXRoutineOneMxy.Finish' at Center.", repo.SnapXRoutineOneMxy.FinishInfo, new RecordItemIndex(22));
            //repo.SnapXRoutineOneMxy.Finish.Click();
            //Delay.Milliseconds(200);

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SNAPX.SNAPX' at 28;6.", repo.SNAPX.SNAPXInfo, new RecordItemIndex(23));
            //repo.SNAPX.SNAPX.Click("28;6");
            //Delay.Milliseconds(200);

            //string strNewPromptTitle = repo.SNAPX.SNAPX.Text;



            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SNAPX.SaveChangesText' at 92;7.", repo.SNAPX.SaveChangesTextInfo, new RecordItemIndex(24));
            //repo.SNAPX.SaveChangesText.Click("92;7");
            //Delay.Milliseconds(200);

            //string strNewpromptText = repo.SNAPX.SaveChangesText.TextValue;


            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'n'.", new RecordItemIndex(25));
            //Keyboard.Press("n");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(26));
            //Delay.Duration(4000, false);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LMenu}'.", new RecordItemIndex(27));
            //Keyboard.Press("{LMenu}");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'F'.", new RecordItemIndex(28));
            //Keyboard.Press("F");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'N'.", new RecordItemIndex(29));
            //Keyboard.Press("N");
            //Delay.Milliseconds(0);

        }

    }
}
